DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'dograh_app') THEN
    CREATE ROLE dograh_app LOGIN PASSWORD 'veyra';
  END IF;
END
$$;
ALTER ROLE dograh_app SET search_path TO public;
ALTER DATABASE template1 REFRESH COLLATION VERSION;
ALTER DATABASE postgres REFRESH COLLATION VERSION;
ALTER DATABASE veyra REFRESH COLLATION VERSION;
DROP SCHEMA IF EXISTS dograh CASCADE;
CREATE EXTENSION IF NOT EXISTS vector;
